version: "3"

services:
  api:
    build: .
    ports:
      - 8080:8080
    scale: 2

  mongodb:
    image: bitnami/mongodb:latest
    ports:
      - 27017
    volumes:
    -  mongodb-data:/bitnami/mongodb

volumes:
  mongodb-data: