# This is a basic workflow to help you get started with Actions

name: Destroying preview environment

# Controls when the workflow will run
on:
  pull_request:
    types:
      - closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  closed:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Login
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Deleting your preview environment
      uses: okteto/destroy-preview@latest
      with:
        name: pr-${{ github.event.number }}-robsonpiere
      
      
