# This is a basic workflow to help you get started with Actions

name: Deploying a Preview Environment

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Login into your Dashboard
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Deploy your preview environment
      uses: okteto/deploy-preview@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-przinho
        scope: personal
        timeout: 15m
        
        
